# This file is used to configure the environment commands.

# This section is used to configure the speed up effect for time fast-forward smoothly over five seconds
speedUpEffect:
  enabled: true

# This section is used to configure the time commands.
times:
  day:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time set to <green>Day</green></white>'
        - '[sound] ui.button.click'

  night:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time set to <green>Night</green></white>'
        - '[sound] ui.button.click'

weather:
  rain:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Rain</green></white>'
        - '[sound] ui.button.click'

  thunder:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Thunder</green></white>'
        - '[sound] ui.button.click'

  sun:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Sun</green></white>'
        - '[sound] ui.button.click'

# This section is used to configure the locktime command, which freezes the current
# world's time until unlocked with /locktime off.
locktime:
  day:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time locked at <green>Day</green></white>'
        - '[sound] ui.button.click'

  night:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time locked at <green>Night</green></white>'
        - '[sound] ui.button.click'

  noon:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time locked at <green>Noon</green></white>'
        - '[sound] ui.button.click'

  midnight:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time locked at <green>Midnight</green></white>'
        - '[sound] ui.button.click'

  custom:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time locked</white>'
        - '[sound] ui.button.click'

  off:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time unlocked</white>'
        - '[sound] ui.button.click'
